In [1]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 =  np.array(data1)
print(arr1)
print(arr1.dtype)
print(arr1.shape)
print(arr1.ndim)


[6.  7.5 8.  0.  1. ]
float64
(5,)
1


In [2]:
import numpy as np

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]  #list of lists
arr2 = np.array(data2)
print(arr2.ndim)   #2
print(arr2.shape)  # (2,4)


2
(2, 4)


In [6]:
array = np.eye(3) 
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
array = np.random.randint(0, 10, (3,3))
print(array)

[[8 8 5]
 [5 2 3]
 [2 8 0]]


In [17]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print("-----------")
print(arr * arr)
print("-----------")
print(arr - arr)


[[1. 2. 3.]
 [4. 5. 6.]]
-----------
[[ 1.  4.  9.]
 [16. 25. 36.]]
-----------
[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
arr = np.array([[2,4,6],[8,10,12],[14,16,18]])
print(arr)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [37]:
print(arr[:,-1])

[ 6 12 18]
